name: CI WordleOfGod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: proulxsamuel/deploy-blazor-to-gh-pages@master
        with:
          project_path: 'WordleOfGod'
